#!/bin/bash

NAME="$1"
COUNT="$2"

while [ -z "$NAME" ]; do read -p "NAME: " NAME; done
while [ -z "$COUNT" ]; do read -p "NAME: " COUNT; done

for (( c=1; c<=$COUNT; c++ ))
do
	echo -e "$(randmac) $NAME-$RANDOM"
done
