#!/bin/bash

# fonts
[ ! -e "$HOME/.local/share/fonts" ] && ln -sfr "$HOME/.vip/fonts" "$HOME/.local/share/fonts"

# scripts
ln -sfr "$HOME/.vip/tools/beep/beep"                              "$HOME/.vip/scripts/beep"
ln -sfr "$HOME/.vip/tools/beep-keyboard/beep-keyboard"            "$HOME/.vip/scripts/beep-keyboard"
ln -sfr "$HOME/.vip/pyenv/p3tools/IPGeoLocation/ipgeolocation.py" "$HOME/.vip/scripts/ipgeolocation"
ln -sfr "$HOME/.vip/tools/slowloris/slowloris"                    "$HOME/.vip/scripts/slowloris"
ln -sfr "$HOME/.vip/tools/xkblayout-state/xkblayout-state"        "$HOME/.vip/scripts/xkblayout-state"
ln -sfr "$HOME/.vip/tools/dahvore/dahvore"                        "$HOME/.vip/scripts/dahvore"
ln -sfr "$HOME/.vip/tools/wlan-deauth/wlan-deauth.py"             "$HOME/.vip/scripts/wlan-deauth"
