#!/bin/bash
FILE_INPUT="$1"
FILE_OUTPUT="$2"
while [ -z "$FILE_INPUT"  ]; do read -r -p "Input File..: " FILE_INPUT  ; done
while [ -z "$FILE_OUTPUT" ]; do read -r -p "Output File.: " FILE_OUTPUT ; done
ffmpeg -i "$FILE_INPUT" -map_metadata -1 -c:v copy -c:a copy "$FILE_OUTPUT"
