#!/bin/dash

FILE="$1"
SSID="$2"
PASS="$3"

while [ -z "$FILE" ]; do read -r -p 'FILE: ' FILE ; done
while [ -z "$SSID" ]; do read -r -p 'SSID: ' SSID ; done
while [ -z "$PASS" ]; do read -r -p 'PASS: ' PASS ; done

if echo "$SSID" | grep ":" > /dev/null 2>/dev/null; then
	echo "$3" | aircrack-ng "$FILE" -b "$SSID" -w -
else
	echo "$3" | aircrack-ng "$FILE" -e "$SSID" -w -
fi
