#!/bin/bash
FILE="$HOME/.vip/lists/personal/stations"
link="$(< "$FILE" fzf --layout=reverse)"
[ -z "$link" ] && exit

RUN() {
	if ! mpv --volume=50 --geometry=100%:100% --autofit-larger=700 "${link%% *}"; then RUN; fi
}

RUN
