#!/bin/sh
grep -v "#" "$HOME/.vip/lists/tables/emoji" | rofi -theme sidebar -l 20 -font "Cantarell 18" -p "" -dmenu -i | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
text="$(xclip -o -selection clipboard)"
[ -z "$text" ] || notify-send -a "EMOJI TABLE" -t 2000 "clipboard: \"$(xclip -o -selection clipboard)\""



