#!/bin/bash

ICON=""
VOL1=""
VOL2=""
VOL3=""
VOLM=""

case $BLOCK_BUTTON in
  1) ~/.config/i3/scripts/voldo -t >/dev/null 2>/dev/null ;;   # mute
  3) pavucontrol </dev/null &>/dev/null & ;;                   # start pulse audio control
  4) ~/.config/i3/scripts/voldo -i 5 >/dev/null 2>/dev/null ;; # scroll up, increase
  5) ~/.config/i3/scripts/voldo -d 5 >/dev/null 2>/dev/null ;; # scroll down, decrease
esac

volume="$(pamixer --get-volume)"

if [ "$(pamixer --get-mute)" == "true" ]; then
	ICON="$VOLM"
else
	if   [ $volume -ge 55 ]; then ICON="$VOL3"
	elif [ $volume -ge 15 ]; then ICON="$VOL2"
	else ICON="$VOL1" ; fi
fi

echo -e "$ICON $volume"
