#!/bin/bash

case $BLOCK_BUTTON in
	1) notify-send -i "/usr/share/icons/gnome/48x48/status/connect_established.png" -a "WIFI" -t 5000 "$(echo -e "IP(s)....: $(hostname_I)\nGATEWAYS.: $(gateways)")"  ;;
	3) terminator -e "nmcli ; read -n1" </dev/null &>/dev/null & ;;
esac

hostname_I
