#!/bin/bash

case $BLOCK_BUTTON in
  1) i3keyboard_switch ;;
esac

keyb="$(xkblayout-state print "%n%v")"
if [ "$keyb" == "English" ]; then
	echo -e "[US],RS,RSL"
elif [ "$keyb" == "Serbian" ]; then
	echo -e "US,[RS],RSL"
elif [ "$keyb" == "Serbianlatin" ]; then
	echo -e "US,RS,[RSL]"
fi
