#!/bin/bash
ESSID="$1"
PASSWORD="$2"
while [ -z "$ESSID" ];    do read -p 'ESSID: ' ESSID       ; done
while [ -z "$PASSWORD" ]; do read -p 'PASSWORD: ' PASSWORD ; done
nmcli dev wifi connect "$ESSID" password "$PASSWORD"
