#!/bin/bash

#DEFINE:
WIFI_ESSID="$1"
CHANNEL="$2"
WIFI_BSSID="$3"

wlan mon

if [ -z "$WIFI_ESSID" ]; then
	read -p 'ESSID: ' WIFI_ESSID
fi

if [ -z "$CHANNEL" ]; then
	read -p 'CH: ' CHANNEL
fi

if [ -z "$WIFI_BSSID" ]; then
	read -p 'BSSID: ' WIFI_BSSID
fi

airbase-ng -a "$WIFI_BSSID" --essid "$WIFI_ESSID" -c "$CHANNEL" "$(wlanDevice mon)"
