#!/bin/bash
grep -v "#" ~/.lists/emoji | rofi -theme Monokai -lines 20 -p "" -dmenu -i | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
text="$(xclip -o -selection clipboard)"
[ -z "$text" ] || notify-send -a "EMOJI TABLE" -t 2000 "\"$(xclip -o -selection clipboard)\" copied to clipboard."



