#!/bin/bash

# set "random" wallpaper depending on date/time
# night time - dark wallpaper
# day time   - light wallpaper
# special day wallpapers (WWI, WWII, 4th of july, ...)
# season of the year wallpapers (winter, spring, summer, autumn)

