#!/bin/bash

# set "random" wallpaper depending on date/time

bgdir_day="/home/user/Pictures/Wallpapers/Day"
bgdir_night="/home/user/Pictures/Wallpapers/Night"
bgdir_dark="/home/user/Pictures/Wallpapers/Dark"

hour="$(date +"%H")"

if [ $hour -ge 20 ]; then
	feh --recursive --randomize --bg-fill "$bgdir_dark"
elif [ $hour -ge 16 ]; then
	feh --recursive --randomize --bg-fill "$bgdir_night"
else
	feh --recursive --randomize --bg-fill "$bgdir_day"
fi


